export const ADD_NGREDIENT = 'ADD_NGREDIENT';
export const REMOVE_NGREDIENT = 'REMOVE_NGREDIENT';
export const SET_INGREDINETS = 'SET_INGREDINETS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';